// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		double x;
		int lessthanhalf = 0;
		int morethanhalf = 0;
		for(int i = 0; i < n; i++)
		{
			x = Math.random();
			if(x <= 0.5)
			{
				lessthanhalf++;
			}
			else morethanhalf++;
		}
		double max = Math.max(morethanhalf, lessthanhalf);
		double min = Math.min(morethanhalf,lessthanhalf);

		System.out.println("> 0.5: " + morethanhalf + " times");
		System.out.println("<= 0.5: " + lessthanhalf + " times");
		System.out.println("Ratio: " + min/max);
	}
}
